version: '3'

services:

#  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # volumes:
    #   - ./db-data/postgres/:/var/lib/postgresql/data/

  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    # volumes:
    #   - ./db-data/redis/:/data

  #  start minio, and ensure that data is stored to a mounted volume
  minio:
    image: 'quay.io/minio/minio'
    command: server /mnt/data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    # volumes:
    #   - ./db-data/minio/:/mnt/data/

  #  start MariaDB, and ensure that data is stored to a mounted volume
  mariadb:
    image: 'mariadb:10.6'
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: storageapp
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: password

    volumes:
      - ./db-data/mariadb/:/var/lib/mysql
